FROM node:18

# Set timezone
ENV TZ Europe/Paris

# Set default shell
ENV SHELL /bin/bash

# Set working directory
WORKDIR /home/client

# Copy package.json and package-lock.json first
COPY ./client/package*.json .

# Install dependencies
RUN npm install

# Install Playwright dependencies and browser binaries for Chromium, Firefox and WebKit (Safari)
RUN npx -y playwright install --with-deps

# Copy the rest of the application code
COPY ./client .

# Install TypeScript and ts-node globally
ENV SHELL /bin/bash

# Expose the port that Vite uses
EXPOSE 5173

# Start the application
CMD ["/bin/bash"]