FROM node:18

# Set timezone
ENV TZ Europe/Paris

# Set default shell
ENV SHELL /bin/bash

# Set working directory
WORKDIR /home/client

# Copy package.json and package-lock.json first
COPY ./client/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY ./client .

# Build the application
RUN npm run build:staging

# Expose the port that Vite uses
EXPOSE 5172

# Start the application
CMD ["npm", "run", "preview"]